name: Epic
description: Create an epic
title: "As a <user> I want to <something> so that I can <something>"
labels: ["epic"]
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: User Stories
    validations:
      required: true
  - type: textarea
    attributes:
      label: Dependencies
